#!/usr/bin/env bash
# scripts/build.sh — Bundle project into a single portable script in bin/
#
# Usage: ./scripts/build.sh [VERSION] [COMMIT] [BUILD_TIME]

set -euo pipefail

VERSION="${1:-dev}"
COMMIT="${2:-$(git rev-parse --short HEAD 2>/dev/null || echo 'unknown')}"
BUILD_TIME="${3:-$(date -u '+%Y-%m-%d_%H:%M:%S')}"
BASH_VER="$(bash --version | head -1 | awk '{print $4}')"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
BIN_DIR="$PROJECT_ROOT/bin"
BINARY_NAME="${BINARY_NAME:-bash-template}"

mkdir -p "$BIN_DIR"

OUTPUT="$BIN_DIR/$BINARY_NAME"

echo "Building $BINARY_NAME v$VERSION"
echo "  Commit: $COMMIT"
echo "  Build Time: $BUILD_TIME"

# Build a single bundled script by inlining all libraries
{
    echo '#!/usr/bin/env bash'
    echo '# Auto-generated by scripts/build.sh — do not edit directly'
    echo "# $BINARY_NAME v$VERSION ($COMMIT) built $BUILD_TIME"
    echo 'set -euo pipefail'
    echo ''
    echo "# Injected version info"
    echo "export APP_VERSION=\"$VERSION\""
    echo "export APP_COMMIT=\"$COMMIT\""
    echo "export APP_BUILD_TIME=\"$BUILD_TIME\""
    echo "export APP_BASH_VERSION=\"$BASH_VER\""
    echo ''

    # Inline each library (strip shebangs and set commands to avoid conflicts)
    for lib in "$PROJECT_ROOT"/lib/*.sh; do
        echo "# --- $(basename "$lib") ---"
        sed -e '/^#!/d' -e '/^set -/d' "$lib"
        echo ''
    done

    # Inline commands
    for cmd in "$PROJECT_ROOT"/src/commands/*.sh; do
        echo "# --- commands/$(basename "$cmd") ---"
        sed -e '/^#!/d' -e '/^set -/d' "$cmd"
        echo ''
    done

    # Inline main.sh (strip shebangs, set, and source lines since libraries are inlined)
    echo "# --- main.sh ---"
    sed -e '/^#!/d' \
        -e '/^set -euo/d' \
        -e '/^SCRIPT_DIR=/d' \
        -e '/^PROJECT_ROOT=/d' \
        -e '/^SRC_DIR=/d' \
        -e '/^LIB_DIR=/d' \
        -e '/^source /d' \
        -e '/^[[:space:]]*source /d' \
        -e '/^[[:space:]]*# shellcheck source/d' \
        "$PROJECT_ROOT/src/main.sh"

} >"$OUTPUT"

chmod +x "$OUTPUT"
echo "Built: $OUTPUT"
